# Generated by Django 3.1.1 on 2020-10-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0003_adapt_max_tag_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='object_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Object Key'),
        ),
    ]
